import 'package:freezed_annotation/freezed_annotation.dart';
import 'time_block.dart';
import 'routine_explanation.dart';

part 'routine.freezed.dart';
part 'routine.g.dart';

/// Daily routine model
///
/// Represents a complete daily routine with time blocks, generated by
/// on-device AI based on calendar events, sleep data, and weather.
@freezed
abstract class Routine with _$Routine {
  const factory Routine({
    required String id,
    required DateTime date,
    required String title,
    required List<TimeBlock> timeBlocks,
    RoutineExplanation? explanation,
    double? confidenceScore,
    @Default(false) bool isAccepted,
    required DateTime createdAt,
    required DateTime updatedAt,
  }) = _Routine;

  factory Routine.fromJson(Map<String, dynamic> json) =>
      _$RoutineFromJson(json);
}

/// Extension methods for Routine
extension RoutineX on Routine {
  /// Check if routine is for today
  bool get isToday {
    final now = DateTime.now();
    return date.year == now.year &&
        date.month == now.month &&
        date.day == now.day;
  }

  /// Get total duration of all time blocks in minutes
  int get totalDurationMinutes {
    return timeBlocks.fold(
      0,
      (sum, block) => sum + block.durationMinutes,
    );
  }

  /// Get time blocks by activity type
  List<TimeBlock> getBlocksByType(String activityType) {
    return timeBlocks.where((block) => block.activityType == activityType).toList();
  }

  /// Get current time block (if any)
  TimeBlock? getCurrentTimeBlock() {
    final now = DateTime.now();
    for (final block in timeBlocks) {
      if (block.startTime.isBefore(now) && block.endTime.isAfter(now)) {
        return block;
      }
    }
    return null;
  }

  /// Get next time block (if any)
  TimeBlock? getNextTimeBlock() {
    final now = DateTime.now();
    final futureBlocks = timeBlocks
        .where((block) => block.startTime.isAfter(now))
        .toList()
      ..sort((a, b) => a.startTime.compareTo(b.startTime));

    return futureBlocks.isEmpty ? null : futureBlocks.first;
  }

  /// Check if routine has any snoozed blocks
  bool get hasSnoozedBlocks {
    return timeBlocks.any((block) => block.isSnoozed);
  }

  /// Get completion percentage (based on passed time blocks)
  double get completionPercentage {
    final now = DateTime.now();
    final completedBlocks = timeBlocks.where((block) => block.endTime.isBefore(now)).length;
    return timeBlocks.isEmpty ? 0.0 : completedBlocks / timeBlocks.length;
  }
}
